### ISSUE TITLE
Xcode doesn't load the plugin when installing without resigning

### ISSUE THREAD

**Issue by Havhingstor** [wakatime/xcode-wakatime-legacy#64]
I'm running macOS 12.4 and Xcode 13.4 (13F17a).
I have a nearly fresh Xcode-Installation (It was installed previously, but removed via AppCleaner), only the license-agreement got handled as the script prompted me to do so.
I used the script to install without resigning, which didn't show any errors after I agreed to the xcode-license.
If I start up Xcode, it asks me if I want to load the wakatime-plugin, and I clicked "load", but it didn't seem to do so. It didn't ask for my api-key, didn't create the wakatime.cfg-file, nor does ist show wakatime in the files-menu.
I tried running the script a second time, but that didn't change anything except now it didn't ask me, if it should load the plugin.
Then I ran the uninstall-script, which is included in the repository, and the uninstall-section of the README, and then tried again to install, which again didn't show any errors, nor asked me, if I want to load wakatime, but still didn't work.

There was no ~/.wakatime.log-file, 
the Xcode log is:
```
Jun  1 16:54:24 PS-MBA login[4123]: DEAD_PROCESS: 4123 ttys001
Jun  1 16:55:10 PS-MBA login[7272]: USER_PROCESS: 7272 ttys001
Jun  1 16:58:28 PS-MBA AMPDeviceDiscoveryAgent[603]: Entered:_AMMuxedDeviceDisconnected, mux-device:9
Jun  1 16:58:28 PS-MBA AMPDeviceDiscoveryAgent[603]: Entered:__thr_AMMuxedDeviceDisconnected, mux-device:9
Jun  1 16:58:44 PS-MBA syslogd[356]: ASL Sender Statistics
Jun  1 16:58:59 PS-MBA Core Audio Driver (BlackHole2ch.driver)[497]: BlackHole_GetControlPropertyData: the item in the qualifier is not valid for kAudioSelectorControlPropertyItemName for the data source control
Jun  1 16:59:29 --- last message repeated 5 times ---
```

If somebody knows how  to make Xcode load the plugin, or what could be wrong, I'd like to hear.
Thanks.

**Comment by Havhingstor** [comment]
Yes

**Comment by Havhingstor** [comment]
I installed Alcatraz, but it still didn't seem to load wakatime as it didn't ask for the api-key nor shows the menu-item.

**Comment by BillChen2k** [comment]
Same issue here. I'm using Xcode 13.4.1, I followed the instructions including DisableLibraryValidation, installing Alcatraz and installing wakatime with `nosign` flag. I can't see wakatime menu in my Xcode after these steps.

**Comment by AlfinIndrawan** [comment]
do disableLibraryValidation will disable security? how much security it disable?

**Comment by frankois941** [comment]
Same thing, this method doesn't work anymore

**Comment by AlfinIndrawan** [comment]
yes...this doesnt work in new version with no sign method. So i tried to clone steps, it turns out that i dont need another 12 gb for clone (it just take ~2 gb) and it works flawlessly.
